apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
  name: status-badge
spec:
  rules:
  - host: {{ .Values.previewname }}.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: preview-status-badge
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.previewname }}.{{ .Values.domain }}
    secretName: tls-jenkins-x-live-p
